cc_test(
    name = "test",
    srcs = [
        "one_test.cc",
    ],
    deps = [
        "@boost//:filesystem",
        "@boost//:log",
        "@boost//:system",
        "@com_google_googletest//:gtest_main",
    ],
)
